- name: DynamicDNS
  hosts: all
  gather_facts: false
  vars_files:
    - ../vars/main.yml

  tasks:

  - name: Install and configure DynamicDNS
    tags: init
    become: true
    block:

    - name: Install ddclient
      ansible.builtin.apt:
        pkg:
          - ddclient
        state: latest

    - name: Update /etc/ddclient.conf file - Replace a few lines
      ansible.builtin.lineinfile:
        path: /etc/ddclient.conf
        state: present
        search_string: "{{ item.search_string }}"
        line: "{{ item.line }}"
        owner: root
        group: root
        mode: 0600
      loop:
        - { search_string: "^protocol", line: "protocol=dyndns2" }
        - { search_string: "^use", line: "use=web, web=checkip.dyndns.com, web-skip='Current IP Address'" }
        - { search_string: "^login", line: "login={{ dyn_host_username }}" }
        - { search_string: "^password", line: "password={{ dyn_host_password }}" }

    - name: Update /etc/ddclient.conf file - Add a few lines
      ansible.builtin.lineinfile:
        path: /etc/ddclient.conf
        state: present
        line: "{{ item.line }}"
      loop:
        - { line: "ssl=yes" }
        - { line: "server={{ dyn_server }}" }
        - { line: "{{ domain }}" }

    - name: Restart ddclient service
      ansible.builtin.systemd:
        name: ddclient
        state: restarted
        enabled: yes
