- name: NVIDIA
  hosts: all
  gather_facts: false

  tasks:

  - name: Install NVIDIA Container Toolkit
    tags: init
    become: true
    block:

    - name: Create /etc/apt/keyrings directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: 0755

    - name: Add NVIDIA GPG apt key
      ansible.builtin.get_url:
        url: https://nvidia.github.io/libnvidia-container/gpgkey
        dest: /tmp/nvidia-container-toolkit-keyring.gpg
        mode: 0644

    - name: Import NVIDIA GPG key
      ansible.builtin.command: gpg --dearmor -o /etc/apt/keyrings/nvidia-container-toolkit-keyring.gpg /tmp/nvidia-container-toolkit-keyring.gpg

    - name: Configure NVIDIA APT repository
      block:
      - name: Fetch NVIDIA APT repository file
        ansible.builtin.get_url:
          url: https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list
          dest: /tmp/nvidia-container-toolkit.list

      - name: Modify APT repository file
        ansible.builtin.replace:
          path: /tmp/nvidia-container-toolkit.list
          regexp: 'deb https://'
          replace: 'deb [signed-by=/etc/apt/keyrings/nvidia-container-toolkit-keyring.gpg] https://'

      - name: Copy repository file to /etc/apt/sources.list.d/
        ansible.builtin.copy:
          src: /tmp/nvidia-container-toolkit.list
          dest: /etc/apt/sources.list.d/nvidia-container-toolkit.list

    - name: Update apt cache and install NVIDIA Container Toolkit
      ansible.builtin.apt:
        pkg:
          - nvidia-driver-535
          - nvidia-container-toolkit
        state: present
        update_cache: true

    - name: Run toolkit runtime configuration
      ansible.builtin.command: nvidia-ctk runtime configure --runtime=docker

    - name: Restart Docker service
      ansible.builtin.systemd:
        name: docker
        state: restarted
        enabled: yes
