services:
  unbound:
    container_name: unbound
    dns:
      - 127.0.0.1
      - 45.90.28.96
      - 45.90.30.96
    image: ${UNBOUND_IMAGE}
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 10m
    networks:
      dns-net:
        ipv4_address: ${UNBOUND_DNS_IP}
    ports:
      - 5335/tcp
      - 5335/udp
    restart: unless-stopped
    stop_grace_period: 30s
    volumes:
      - ./persistence:/opt/unbound/etc/unbound
      # - ./persistence/forward-records.conf:/opt/unbound/etc/unbound/forward-records.conf:ro
      # - ./persistence/a-records.conf:/opt/unbound/etc/unbound/a-records.conf:ro

networks:
  dns-net:
    external: true
    name: dns-net
