- name: Python
  hosts: all
  gather_facts: false
  vars:
    packages:
      - python3
      - python3-docker # used by Ansible modules
      - python3-passlib # used by Ansible modules
      - python3-pip
      - python3.11-dev
      - python-is-python3
    pip_packages:
      - docker-compose # used by Ansible modules

  tasks:
  # Packages
  - name: Packages
    block:

    - name: List packages
      tags: [init, update]
      ansible.builtin.debug:
        msg: "packages: {{ packages }}"

    # sudo apt update -y && sudo apt install -y
    - name: Install
      tags: init
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
        update_cache: true

    # sudo apt update -y && sudo apt upgrade -y
    - name: Upgrade
      tags: update
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: latest
        update_cache: true

  # PyPI Packages
  - name: PyPI Packages
    block:

    - name: List packages
      tags: [init, update]
      ansible.builtin.debug:
        msg: "PyPI packages: {{ pip_packages }}"

    # pip install
    - name: PyPI - Install packages
      tags: init
      ansible.builtin.pip:
        name: "{{ pip_packages }}"
        state: present

    # pip install --upgrade
    - name: PyPI - Upgrade packages
      tags: update
      ansible.builtin.pip:
        name: "{{ pip_packages }}"
        state: latest
