services:
  db:
    container_name: hortusfox-mariadb
    env_file: config/.env.db
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p${HORTUSFOX_DB_ROOT_PASSWORD}"]
      interval: 20s
      timeout: 15s
      retries: 3
      start_period: 60s
      start_interval: 5s
    hostname: hortusfox-mariadb
    image: ${DEFAULT_DB_IMAGE}
    logging:
      driver: json-file
      options:
        max-file: 2
        max-size: 5m
    networks:
      app-net:
        ipv4_address: ${HORTUSFOX_DB_IP}
    restart: unless-stopped
    stop_grace_period: 30s
    volumes:
      - ./db-persistence:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro

  hortusfox:
    container_name: hortusfox
    depends_on:
      db:
        condition: service_healthy
    dns:
      - 127.0.0.1
      - 45.90.28.96
      - 45.90.30.96
    env_file: config/.env
    hostname: hortusfox
    image: ${HORTUSFOX_IMAGE}
    labels:
      - "traefik.enable=true"
      # Routers
      - "traefik.http.routers.hortusfox.entrypoints=web,websecure"
      - "traefik.http.routers.hortusfox.rule=Host(`plants.${DOMAIN}`)"
      - "traefik.http.routers.hortusfox.tls=true"
      # - "traefik.http.routers.hortusfox.tls.certresolver=letsencrypt"
      # - "traefik.http.routers.hortusfox.tls.domains[0].main=plants.${DOMAIN}"
      - "traefik.http.routers.hortusfox.service=hortusfox"
      # Services
      - "traefik.http.services.hortusfox.loadbalancer.server.port=80"
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 10m
    networks:
      app-net:
        ipv4_address: ${HORTUSFOX_INTERNAL_IP}
      traefik-net:
        ipv4_address: ${HORTUSFOX_IP}
    ports:
      - 80
    restart: unless-stopped
    stop_grace_period: 30s
    volumes:
      - ./persistence/images:/var/www/html/public/img
      - ./persistence/logs:/var/www/html/app/logs
      - ./persistence/backup:/var/www/html/public/backup
      - ./persistence/themes:/var/www/html/public/themes
      - ./persistence/migrate:/var/www/html/app/migrations

networks:
  app-net:
    name: hortusfox-internal
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${HORTUSFOX_NET}
          gateway: ${HORTUSFOX_GATEWAY}
  traefik-net:
    external: true
    name: traefik-net
