- name: Remove home server services
  tags: down
  block:

  - name: Import enable flags
    include_vars:
      file: vars/main.yml

  - name: Remove Traefik
    docker_compose:
      project_src: '{{ server_home }}/services/traefik'
      state: absent

  - name: Remove WireGuard
    when: wireguard_enable
    docker_compose:
      project_src: '{{ server_home }}/services/wireguard'
      state: absent

  - name: Remove Pihole
    when: pihole_enable
    docker_compose:
      project_src: '{{ server_home }}/services/pihole'
      state: absent

  - name: Remove Grafana
    when: grafana_enable
    docker_compose:
      project_src: '{{ server_home }}/services/grafana'
      state: absent

  - name: Remove Ntfy
    when: ntfy_enable
    docker_compose:
      project_src: '{{ server_home }}/services/ntfy'
      state: absent

  - name: Remove Limesurvey
    when: limesurvey_enable
    docker_compose:
      project_src: '{{ server_home }}/services/limesurvey'
      state: absent

  - name: Remove Bitwarden
    when: bitwarden_enable
    docker_compose:
      project_src: '{{ server_home }}/services/bitwarden'
      state: absent

  - name: Remove NextCloud
    when: nextcloud_enable
    docker_compose:
      project_src: '{{ server_home }}/services/nextcloud'
      state: absent

  - name: Remove Photoprism
    when: photoprism_enable
    docker_compose:
      project_src: '{{ server_home }}/services/photoprism'
      state: absent

  - name: Remove Jellyfin
    when: jellyfin_enable
    docker_compose:
      project_src: '{{ server_home }}/services/jellyfin'
      state: absent

  - name: Remove Grocy
    when: grocy_enable
    docker_compose:
      project_src: '{{ server_home }}/services/grocy'
      state: absent

  - name: Remove Minecraft
    when: minecraft_enable
    docker_compose:
      project_src: '{{ server_home }}/services/minecraft'
      state: absent
