- name: Remove home server services
  tags: down
  block:

  - name: Remove Traefik
    docker_compose:
      project_src: "{{ services }}/traefik"
      state: absent

  - name: Remove Bitwarden
    docker_compose:
      project_src: "{{ services }}/bitwarden"
      state: absent

  - name: Remove NextCloud
    docker_compose:
      project_src: "{{ services }}/nextcloud"
      state: absent

  - name: Remove Pihole
    docker_compose:
      project_src: "{{ services }}/pihole"
      state: absent
