- name: Initialize log directories
  tags: docker
  block:

  #--- Logs directory
  - name: Create logs directory
    file:
      path: '{{ server_home }}/logs'
      state: directory
      owner: docker
      group: docker
      mode: 0744

  #--- Services subdirectories
  - name: Create log subdirectories for all services
    file:
      path: '{{ item }}'
      state: directory
      owner: docker
      group: docker
      mode: 0744
    loop:
      - '{{ server_home }}/logs/backup/kopia'
      - '{{ server_home }}/logs/dashboard/homarr'
      - '{{ server_home }}/logs/dns/pihole'
      - '{{ server_home }}/logs/dns/unbound'
      - '{{ server_home }}/logs/finances/actual'
      - '{{ server_home }}/logs/games/minecraft'
      - '{{ server_home }}/logs/inventory/grocy'
      - '{{ server_home }}/logs/inventory/hortusfox'
      - '{{ server_home }}/logs/media/sharing/gokapi'
      - '{{ server_home }}/logs/media/storage/books/kavita'
      - '{{ server_home }}/logs/media/storage/books/librum'
      - '{{ server_home }}/logs/media/storage/documents/nextcloud'
      - '{{ server_home }}/logs/media/storage/documents/paperless'
      - '{{ server_home }}/logs/media/storage/music/navidrome'
      - '{{ server_home }}/logs/media/storage/pictures/immich'
      - '{{ server_home }}/logs/media/storage/pictures/photoprism'
      - '{{ server_home }}/logs/media/storage/videos/jellyfin'
      - '{{ server_home }}/logs/monitoring/detection'
      - '{{ server_home }}/logs/monitoring/grafana'
      - '{{ server_home }}/logs/monitoring/ntfy'
      - '{{ server_home }}/logs/monitoring/prometheus'
      - '{{ server_home }}/logs/password-manager/vaultwarden'
      - '{{ server_home }}/logs/pdf/docuseal'
      - '{{ server_home }}/logs/pdf/stirling-pdf'
      - '{{ server_home }}/logs/remote-access/guacamole'
      - '{{ server_home }}/logs/remote-access/wireguard'
      - '{{ server_home }}/logs/reverse-proxy/traefik'
      - '{{ server_home }}/logs/directus'
      - '{{ server_home }}/logs/limesurvey'
