- name: Initialize log directories
  tags: docker
  block:

  #--- Logs
  - name: Create logs directory
    file:
      path: '{{ server_home }}/logs'
      state: directory
      owner: docker
      group: docker
      mode: 0744

  #--- Services
  - name: Create log subdirectories for all services
    file:
      path: '{{ item }}'
      state: directory
      owner: docker
      group: docker
      mode: 0744
    loop:
      - '{{ server_home }}/logs/detection'
      - '{{ server_home }}/logs/docuseal'
      - '{{ server_home }}/logs/grafana'
      - '{{ server_home }}/logs/grocy'
      - '{{ server_home }}/logs/guacamole'
      - '{{ server_home }}/logs/jellyfin'
      - '{{ server_home }}/logs/limesurvey'
      - '{{ server_home }}/logs/minecraft'
      - '{{ server_home }}/logs/nextcloud'
      - '{{ server_home }}/logs/ntfy'
      - '{{ server_home }}/logs/paperless'
      - '{{ server_home }}/logs/photoprism'
      - '{{ server_home }}/logs/pihole'
      - '{{ server_home }}/logs/prometheus'
      - '{{ server_home }}/logs/traefik'
      - '{{ server_home }}/logs/vaultwarden'
      - '{{ server_home }}/logs/wireguard'
