- name: Initialize persistence directories and files
  tags: docker
  block:

  #--- Traefik
  - name: Create Traefik persistence directory
    file:
      path: '{{ server_home }}/services/traefik/persistence'
      state: directory
      owner: docker
      group: docker
      mode: 0744

  - name: Create traefik log files
    file:
      path: '{{ item }}'
      state: touch
      owner: docker
      group: docker
      mode: 0640
    loop:
      - '{{ server_home }}/services/traefik/persistence/access.log'
      - '{{ server_home }}/services/traefik/persistence/traefik.log'

  #--- Traefik - Testing
  - name: Traefik Testing - Copy Traefik configuration file
    when: local_domain
    copy:
      src: '{{ server_home }}/services/traefik/config_local/traefik.toml'
      dest: '{{ server_home }}/services/traefik/persistence/traefik.toml'
      owner: docker
      group: docker
      mode: 0640

  #--- Traefik - Production
  - name: Traefik Production
    when: not local_domain
    block:

    - name: Create traefik certificates file
      file:
        path: '{{ server_home }}/services/traefik/persistence/acme.json'
        state: touch
        owner: docker
        group: docker
        mode: 0600

    - name: Copy Traefik configuration file
      copy:
        src: '{{ server_home }}/services/traefik/config/traefik.toml'
        dest: '{{ server_home }}/services/traefik/persistence/traefik.toml'
        owner: docker
        group: docker
        mode: 0640

    - name: Add email to traefik.toml
      lineinfile:
        path: '{{ server_home }}/services/traefik/persistence/traefik.toml'
        state: present
        search_string: 'email ='
        line: '  email = "{{ user_email }}"'

    - name: Create traefik users.txt file
      file:
        path: '{{ server_home }}/services/traefik/persistence/users.txt'
        state: touch
        owner: docker
        group: docker
        mode: 0640

    - name: Add a user to users.txt
      community.general.htpasswd:
        path: '{{ server_home }}/services/traefik/persistence/users.txt'
        name: '{{ traefik_user }}'
        password: '{{ traefik_password }}'
        hash_scheme: md5_crypt
        state: present

  #--- Production Services
  - name: Production - Uncomment labels and bind mounts in compose.yaml for all services
    when: not local_domain
    replace:
      path: '{{ item }}'
      regexp: '(^\s*)# -'
      replace: '\1-'
    loop:
      - '{{ server_home }}/services/actual/compose.yaml'
      - '{{ server_home }}/services/dashboard/homarr/compose.yaml'
      - '{{ server_home }}/services/detection/compose.yaml'
      - '{{ server_home }}/services/directus/compose.yaml'
      - '{{ server_home }}/services/docuseal/compose.yaml'
      - '{{ server_home }}/services/grafana/compose.yaml'
      - '{{ server_home }}/services/grocy/compose.yaml'
      - '{{ server_home }}/services/guacamole/compose.yaml'
      - '{{ server_home }}/services/immich/compose.yaml'
      - '{{ server_home }}/services/jellyfin/compose.yaml'
      - '{{ server_home }}/services/kopia/compose.yaml'
      - '{{ server_home }}/services/limesurvey/compose.yaml'
      - '{{ server_home }}/services/navidrome/compose.yaml'
      - '{{ server_home }}/services/nextcloud/compose.yaml'
      - '{{ server_home }}/services/ntfy/compose.yaml'
      - '{{ server_home }}/services/paperless/compose.yaml'
      - '{{ server_home }}/services/photoprism/compose.yaml'
      - '{{ server_home }}/services/pihole/compose.yaml'
      - '{{ server_home }}/services/stirling-pdf/compose.yaml'
      - '{{ server_home }}/services/traefik/compose.yaml'
      - '{{ server_home }}/services/vaultwarden/compose.yaml'

  #--- Actual
  - name: Create Actual persistence directories
    ignore_errors: true
    file:
      path: '{{ server_home }}/services/actual/persistence'
      state: directory
      owner: docker
      group: docker
      mode: 0744

  #--- Detection (changedetection.io)
  - name: Create Change Detection persistence directory
    ignore_errors: true
    file:
      path: '{{ server_home }}/services/detection/persistence'
      state: directory
      owner: docker
      group: docker
      mode: 0744

  #--- Directus
  - name: Create Directus persistence directories
    ignore_errors: true
    file:
      path: '{{ item }}'
      state: directory
      owner: docker
      group: docker
      mode: 0744
    loop:
      - '{{ server_home }}/services/directus/db-persistence'
      - '{{ server_home }}/services/directus/persistence'
      - '{{ server_home }}/services/directus/persistence/uploads'
      - '{{ server_home }}/services/directus/persistence/extensions'

  #--- Docuseal
  - name: Create docuseal persistence directories
    ignore_errors: true
    file:
      path: '{{ item }}'
      state: directory
      owner: docker
      group: docker
      mode: 0744
    loop:
      - '{{ server_home }}/services/docuseal/db-persistence'
      - '{{ server_home }}/services/docuseal/persistence'

  #--- Grafana
  - name: Create Grafana persistence directories
    file:
      path: '{{ item }}'
      state: directory
      owner: docker
      group: docker
      mode: 0744
    loop:
      - '{{ server_home }}/services/grafana/persistence'
      - '{{ server_home }}/services/grafana/influxdb-persistence'

  #--- Grocy
  - name: Create Grocy persistence directory
    file:
      path: '{{ server_home }}/services/grocy/persistence'
      state: directory
      owner: docker
      group: docker
      mode: 0744

  #--- Guacamole
  - name: Create Guacamole persistence directories
    file:
      path: '{{ item }}'
      state: directory
      owner: docker
      group: docker
      mode: 0744
    loop:
      - '{{ server_home }}/services/guacamole/db-persistence'
      - '{{ server_home }}/services/guacamole/guacd-persistence'
      - '{{ server_home }}/services/guacamole/guacd-persistence/drive'
      - '{{ server_home }}/services/guacamole/guacd-persistence/record'

  - name: Make initdb.sql script executable
    file:
      path: '{{ server_home }}/services/guacamole/config/initdb.sql'
      state: file
      owner: docker
      group: docker
      mode: 0777

  #--- Homarr
  - name: Create Homarr persistence directories
    file:
      path: '{{ item }}'
      state: directory
      owner: docker
      group: docker
      mode: 0744
    loop:
     - '{{ server_home }}/services/dashboard/homarr/persistence'
     - '{{ server_home }}/services/dashboard/homarr/persistence/configs'
     - '{{ server_home }}/services/dashboard/homarr/persistence/data'
     - '{{ server_home }}/services/dashboard/homarr/persistence/icons'

  #--- Immich
  - name: Create Immich persistence directories
    file:
      path: '{{ item }}'
      state: directory
      owner: docker
      group: docker
      mode: 0744
    loop:
     - '{{ server_home }}/services/immich/db-persistence'
     - '{{ server_home }}/services/immich/persistence'
     - '{{ server_home }}/services/immich/persistence/upload'
     - '{{ server_home }}/services/immich/persistence/model-cache'

  #--- Jellyfin
  - name: Create Jellyfin persistence directories
    file:
      path: '{{ item }}'
      state: directory
      owner: docker
      group: docker
      mode: 0744
    loop:
     - '{{ server_home }}/services/jellyfin/persistence'
     - '{{ server_home }}/services/jellyfin/persistence/library'
     - '{{ server_home }}/services/jellyfin/persistence/tvshows'
     - '{{ server_home }}/services/jellyfin/persistence/movies'

  #--- Kopia
  - name: Create Kopia persistence directories
    ignore_errors: true
    file:
      path: '{{ item }}'
      state: directory
      owner: docker
      group: docker
      mode: 0744
    loop:
      - '{{ server_home }}/services/kopia/persistence'
      - '{{ server_home }}/services/kopia/persistence/config'
      - '{{ server_home }}/services/kopia/persistence/cache'
      - '{{ server_home }}/services/kopia/persistence/logs'
      - '{{ server_home }}/services/kopia/persistence/data'

  #--- Librum
  - name: Create Librum persistence directories
    ignore_errors: true
    file:
      path: '{{ item }}'
      state: directory
      owner: docker
      group: docker
      mode: 0744
    loop:
      - '{{ server_home }}/services/librum/db-persistence'
      - '{{ server_home }}/services/librum/persistence'

  #--- Limesurvey
  - name: Create Limesurvey persistence directories
    ignore_errors: true
    file:
      path: '{{ item }}'
      state: directory
      owner: docker
      group: docker
      mode: 0744
    loop:
      - '{{ server_home }}/services/limesurvey/db-persistence'
      - '{{ server_home }}/services/limesurvey/persistence'
      - '{{ server_home }}/services/limesurvey/persistence/plugins'
      - '{{ server_home }}/services/limesurvey/persistence/upload'
      - '{{ server_home }}/services/limesurvey/persistence/config'

  #--- Minecraft
  - name: Create Minecraft persistence directory
    file:
      path: '{{ server_home }}/services/minecraft/persistence'
      state: directory
      owner: docker
      group: docker
      mode: 0744

  #--- Navidrome
  - name: Create Navidrome persistence directories
    ignore_errors: true
    file:
      path: '{{ item }}'
      state: directory
      owner: docker
      group: docker
      mode: 0744
    loop:
      - '{{ server_home }}/services/navidrome/persistence/data'
      - '{{ server_home }}/services/navidrome/persistence/music'

  #--- Nextcloud
  - name: Create Nextcloud persistence directories
    ignore_errors: true
    file:
      path: '{{ item }}'
      state: directory
      owner: docker
      group: docker
      mode: 0744
    loop:
      - '{{ server_home }}/services/nextcloud/db-persistence'
      - '{{ server_home }}/services/nextcloud/persistence'
      - '{{ server_home }}/services/nextcloud/web-persistence'

  #--- Ntfy
  - name: Create Ntfy persistence directories
    file:
      path: '{{ item }}'
      state: directory
      owner: docker
      group: docker
      mode: 0744
    loop:
      - '{{ server_home }}/services/ntfy/persistence'
      - '{{ server_home }}/services/ntfy/persistence/cache'
      - '{{ server_home }}/services/ntfy/persistence/etc'
      - '{{ server_home }}/services/ntfy/persistence/log'

  - name: Copy Ntfy server configuration file
    copy:
      src: '{{ server_home }}/services/ntfy/config/server.yml'
      dest: '{{ server_home }}/services/ntfy/persistence/etc/server.yml'
      owner: docker
      group: docker
      mode: 0640

  #--- Paperless
  - name: Create Paperless persistence directories
    ignore_errors: true
    file:
      path: '{{ item }}'
      state: directory
      owner: docker
      group: docker
      mode: 0744
    loop:
      - '{{ server_home }}/services/paperless/db-persistence'
      - '{{ server_home }}/services/paperless/persistence/consume'
      - '{{ server_home }}/services/paperless/persistence/data'
      - '{{ server_home }}/services/paperless/persistence/export'
      - '{{ server_home }}/services/paperless/persistence/media'
      - '{{ server_home }}/services/paperless/redis-persistence'

  #--- Photoprism
  - name: Create Photoprism persistence directories
    ignore_errors: true
    file:
      path: '{{ item }}'
      state: directory
      owner: docker
      group: docker
      mode: 0744
    loop:
      - '{{ server_home }}/services/photoprism/db-persistence'
      - '{{ server_home }}/services/photoprism/persistence'
      - '{{ server_home }}/services/photoprism/persistence/pictures'
      - '{{ server_home }}/services/photoprism/persistence/storage'

  #--- Pihole
  - name: Create Pihole directories
    ignore_errors: true
    file:
      path: '{{ item }}'
      state: directory
      owner: docker
      group: docker
      mode: 0744
    loop:
      - '{{ server_home }}/services/pihole/etc-pihole'
      - '{{ server_home }}/services/pihole/etc-dnsmasqd'

  - name: Create Pihole log file
    file:
      path: '{{ server_home }}/services/pihole/pihole.log'
      state: touch
      owner: docker
      group: docker
      mode: 0640

  #--- Prometheus
  - name: Create Prometheus persistence directory
    file:
      path: '{{ server_home }}/services/prometheus/prometheus-persistence'
      state: directory
      owner: docker
      group: docker
      mode: 0744

  #--- Stirling PDF
  - name: Create Stirling PDF persistence directories
    ignore_errors: true
    file:
      path: '{{ item }}'
      state: directory
      owner: docker
      group: docker
      mode: 0744
    loop:
      - '{{ server_home }}/services/stirling-pdf/persistence'
      - '{{ server_home }}/services/stirling-pdf/persistence/tessdata'
      - '{{ server_home }}/services/stirling-pdf/persistence/configs'

  - name: Download French language pack for OCR feature
    get_url:
      url: https://github.com/tesseract-ocr/tessdata/blob/main/fra.traineddata
      dest: '{{ server_home }}/services/stirling-pdf/persistence/tessdata/fra.traineddata'
      mode: 0740

  #--- Unbound
  - name: Create Unbound persistence directory
    ignore_errors: true
    file:
      path: '{{ server_home }}/services/dns/unbound/persistence'
      state: directory
      owner: docker
      group: docker
      mode: 0744

  - name: Copy Unbound server configuration files
    copy:
      src: '{{ item.src }}'
      dest: '{{ item.dst }}'
      owner: docker
      group: docker
      mode: 0640
    loop:
      - { src: '{{ server_home }}/services/dns/unbound/config/forward-records.conf', dst: '{{ server_home }}/services/dns/unbound/persistence/forward-records.conf' }
      - { src: '{{ server_home }}/services/dns/unbound/config/unbound.conf', dst: '{{ server_home }}/services/dns/unbound/persistence/unbound.conf' }

  #--- Vaultwarden
  - name: Create Vaultwarden persistence directories
    ignore_errors: true
    file:
      path: '{{ item }}'
      state: directory
      owner: docker
      group: docker
      mode: 0744
    loop:
      - '{{ server_home }}/services/vaultwarden/db-persistence'
      - '{{ server_home }}/services/vaultwarden/persistence'

  #--- WireGuard
  - name: Create WireGuard persistence directory
    file:
      path: '{{ server_home }}/services/wireguard/persistence'
      state: directory
      owner: docker
      group: docker
      mode: 0744
