#--- Traefik

- name: Create Traefik persistence directory
  file:
    path: "{{ services }}/traefik/persistence"
    state: present
    owner: docker
    group: docker
    mode: 0744
  tags: init

#--- Bitwarden

- name: Create Bitwarden persistence directory
  file:
    path: "{{ services }}/bitwarden/persistence"
    state: present
    owner: docker
    group: docker
    mode: 0744
  tags: init

- name: Create Bitwarden database persistence directory
  file:
    path: "{{ services }}/bitwarden/db-persistence"
    state: present
    owner: docker
    group: docker
    mode: 0744
  tags: init

#--- Nextcloud

- name: Create Nextcloud persistence directory
  file:
    path: "{{ services }}/nextcloud/persistence"
    state: present
    owner: docker
    group: docker
    mode: 0744
  tags: init

- name: Create Nextcloud database persistence directory
  file:
    path: "{{ services }}/nextcloud/db-persistence"
    state: present
    owner: docker
    group: docker
    mode: 0744
  tags: init

- name: Create Nextcloud web persistence directory
  file:
    path: "{{ services }}/nextcloud/web-persistence"
    state: present
    owner: docker
    group: docker
    mode: 0744
  tags: init

#--- Pihole

- name: Create Pihole log file
  file:
    path: "{{ services }}/pihole/pihole.log"
    state: touch
    owner: docker
    group: docker
    mode: 0744
  tags: init

- name: Create Pihole etc directory
  file:
    path: "{{ services }}/pihole/etc-pihole"
    state: present
    owner: docker
    group: docker
    mode: 0744
  tags: init

- name: Create Pihole dsnmasqd directory
  file:
    path: "{{ services }}/pihole/etc-dnsmasqd"
    state: present
    owner: docker
    group: docker
    mode: 0744
  tags: init

#---
