- name: Initialize persistence directories and files
  tags: docker
  block:
  
  #--- Traefik
  - name: Create Traefik persistence directory
    file:
      path: "{{ services }}/traefik/persistence"
      state: directory
      owner: docker
      group: docker
      mode: 0744

  #--- Bitwarden
  - name: Create Bitwarden persistence directory
    file:
      path: "{{ services }}/bitwarden/persistence"
      state: directory
      owner: docker
      group: docker
      mode: 0744
  - name: Create Bitwarden database persistence directory
    file:
      path: "{{ services }}/bitwarden/db-persistence"
      state: directory
      owner: docker
      group: docker
      mode: 0744

  #--- Nextcloud
  - name: Create Nextcloud persistence directory
    file:
      path: "{{ services }}/nextcloud/persistence"
      state: directory
      owner: docker
      group: docker
      mode: 0744
  - name: Create Nextcloud database persistence directory
    file:
      path: "{{ services }}/nextcloud/db-persistence"
      state: directory
      owner: docker
      group: docker
      mode: 0744
  - name: Create Nextcloud web persistence directory
    file:
      path: "{{ services }}/nextcloud/web-persistence"
      state: directory
      owner: docker
      group: docker
      mode: 0744

  #--- Pihole
  - name: Create Pihole log file
    file:
      path: "{{ services }}/pihole/pihole.log"
      state: touch
      owner: docker
      group: docker
      mode: 0744
  - name: Create Pihole etc directory
    file:
      path: "{{ services }}/pihole/etc-pihole"
      state: directory
      owner: docker
      group: docker
      mode: 0744
  - name: Create Pihole dsnmasqd directory
    file:
      path: "{{ services }}/pihole/etc-dnsmasqd"
      state: directory
      owner: docker
      group: docker
      mode: 0744

  #---
