#--- Traefik

- name: Create Traefik persistence directory
  file:
    path: "{{ server_home }}/services/traefik/persistence"
    state: present
    owner: docker
    group: docker
    mode: '0744'
  tags: init

#--- Bitwarden

- name: Create Bitwarden persistence directory
  file:
    path: "{{ server_home }}/services/bitwarden/persistence"
    state: present
    owner: docker
    group: docker
    mode: '0744'
  tags: init

- name: Create Bitwarden database persistence directory
  file:
    path: "{{ server_home }}/services/bitwarden/db-persistence"
    state: present
    owner: docker
    group: docker
    mode: '0744'
  tags: init

#--- Nextcloud

- name: Create Nextcloud persistence directory
  file:
    path: "{{ server_home }}/services/nextcloud/persistence"
    state: present
    owner: docker
    group: docker
    mode: '0744'
  tags: init

- name: Create Nextcloud database persistence directory
  file:
    path: "{{ server_home }}/services/nextcloud/db-persistence"
    state: present
    owner: docker
    group: docker
    mode: '0744'
  tags: init

- name: Create Nextcloud web persistence directory
  file:
    path: "{{ server_home }}/services/nextcloud/web-persistence"
    state: present
    owner: docker
    group: docker
    mode: '0744'
  tags: init

#---
