- name: Restart home server services
  tags: restart
  block:

  - name: Import enable flags
    include_vars:
      file: vars/main.yml

  - name: Restart Traefik
    docker_compose:
      project_src: "{{ services }}/traefik"
      restarted: true
      state: present

  - name: Restart Bitwarden
    when: '{{ bitwarden_enable }}'
    docker_compose:
      project_src: "{{ services }}/bitwarden"
      restarted: true
      state: present

  - name: Restart NextCloud
    when: '{{ nextcloud_enable }}'
    docker_compose:
      project_src: "{{ services }}/nextcloud"
      restarted: true
      state: present

  - name: Restart Pihole
    when: '{{ pihole_enable }}'
    docker_compose:
      project_src: "{{ services }}/pihole"
      restarted: true
      state: present

  - name: Restart Jellyfin
    when: '{{ jellyfin_enable }}'
    docker_compose:
      project_src: "{{ services }}/jellyfin"
      restarted: true
      state: present
