- name: Restart home server services
  tags: restart
  block:

  - name: Import enable flags
    include_vars:
      file: vars/main.yml

  - name: Restart Traefik
    docker_compose:
      project_src: '{{ server_home }}/services/traefik'
      restarted: true
      state: present

  - name: Restart WireGuard
    when: wireguard_enable
    docker_compose:
      project_src: '{{ server_home }}/services/wireguard'
      restarted: true
      state: present

  - name: Restart Guacamole
    when: guacamole_enable
    docker_compose:
      project_src: '{{ server_home }}/services/guacamole'
      restarted: true
      state: present

  - name: Restart Pihole
    when: pihole_enable
    docker_compose:
      project_src: '{{ server_home }}/services/pihole'
      restarted: true
      state: present

  - name: Restart Grafana
    when: grafana_enable
    docker_compose:
      project_src: '{{ server_home }}/services/grafana'
      restarted: true
      state: present

  - name: Restart Prometheus
    when: prometheus_enable
    docker_compose:
      project_src: '{{ server_home }}/services/prometheus'
      restarted: true
      state: present

  - name: Restart Ntfy
    when: ntfy_enable
    docker_compose:
      project_src: '{{ server_home }}/services/ntfy'
      restarted: true
      state: present

  - name: Restart Change Detection
    when: change_detection_enable
    docker_compose:
      project_src: '{{ server_home }}/services/detection'
      restarted: true
      state: present

  - name: Restart NextCloud
    when: nextcloud_enable
    docker_compose:
      project_src: '{{ server_home }}/services/nextcloud'
      restarted: true
      state: present

  - name: Restart Paperless NGX
    when: paperless_enable
    docker_compose:
      project_src: '{{ server_home }}/services/paperless'
      restarted: true
      state: present

  - name: Restart Docuseal
    when: docuseal_enable
    docker_compose:
      project_src: '{{ server_home }}/services/docuseal'
      restarted: true
      state: present

  - name: Restart Photoprism
    when: photoprism_enable
    docker_compose:
      project_src: '{{ server_home }}/services/photoprism'
      restarted: true
      state: present

  - name: Restart Jellyfin
    when: jellyfin_enable
    docker_compose:
      project_src: '{{ server_home }}/services/jellyfin'
      restarted: true
      state: present

  - name: Restart Vaultwarden
    when: vaultwarden_enable
    docker_compose:
      project_src: '{{ server_home }}/services/vaultwarden'
      restarted: true
      state: present

  - name: Restart Kopia
    when: kopia_enable
    docker_compose:
      project_src: '{{ server_home }}/services/kopia'
      restarted: true
      state: present

  - name: Restart Grocy
    when: grocy_enable
    docker_compose:
      project_src: '{{ server_home }}/services/grocy'
      restarted: true
      state: present

  - name: Restart Minecraft
    when: minecraft_enable
    docker_compose:
      project_src: '{{ server_home }}/services/minecraft'
      restarted: true
      state: present

  - name: Restart Limesurvey
    when: limesurvey_enable
    docker_compose:
      project_src: '{{ server_home }}/services/limesurvey'
      restarted: true
      state: present
