- name: Restart Traefik
  docker_compose:
    project_src: "{{ services }}/traefik"
    restarted: true
    state: present
  tags: restart

- name: Restart Bitwarden
  docker_compose:
    project_src: "{{ services }}/bitwarden"
    restarted: true
    state: present
  tags: restart

- name: Restart NextCloud
  docker_compose:
    project_src: "{{ services }/nextcloud"
    restarted: true
    state: present
  tags: restart

- name: Restart Pihole
  docker_compose:
    project_src: "{{ services }/pihole"
    restarted: true
    state: present
  tags: restart
