- name: Restart home server services
  tags: restart
  block:

  - name: Import enable flags
    include_vars:
      file: vars/main.yml

  - name: Docker compose restart
    when: '{{ item.when }}'
    docker_compose:
      project_src: '{{ item.project_src }}'
      restarted: true
      state: present
    loop:
      - { when: true, project_src: '{{ server_home }}/services/traefik' }
      - { when: homarr_enable, project_src: '{{ server_home }}/services/dashboard/homarr' }
      - { when: wireguard_enable, project_src: '{{ server_home }}/services/wireguard' }
      - { when: guacamole_enable, project_src: '{{ server_home }}/services/guacamole' }
      - { when: pihole_enable, project_src: '{{ server_home }}/services/pihole' }
      - { when: grafana_enable, project_src: '{{ server_home }}/services/grafana' }
      - { when: prometheus_enable, project_src: '{{ server_home }}/services/prometheus' }
      - { when: ntfy_enable, project_src: '{{ server_home }}/services/ntfy' }
      - { when: change_detection_enable, project_src: '{{ server_home }}/services/detection' }
      - { when: kopia_enable, project_src: '{{ server_home }}/services/kopia' }
      - { when: nextcloud_enable, project_src: '{{ server_home }}/services/nextcloud' }
      - { when: paperless_enable, project_src: '{{ server_home }}/services/paperless' }
      - { when: librum_enable, project_src: '{{ server_home }}/services/librum' }
      - { when: photoprism_enable, project_src: '{{ server_home }}/services/photoprism' }
      - { when: immich_enable, project_src: '{{ server_home }}/services/immich' }
      - { when: navidrome_enable, project_src: '{{ server_home }}/services/navidrome' }
      - { when: jellyfin_enable, project_src: '{{ server_home }}/services/jellyfin' }
      - { when: vaultwarden_enable, project_src: '{{ server_home }}/services/vaultwarden' }
      - { when: actual_enable, project_src: '{{ server_home }}/services/actual' }
      - { when: grocy_enable, project_src: '{{ server_home }}/services/grocy' }
      - { when: docuseal_enable, project_src: '{{ server_home }}/services/docuseal' }
      - { when: stirling_pdf_enable, project_src: '{{ server_home }}/services/stirling-pdf' }
      - { when: minecraft_enable, project_src: '{{ server_home }}/services/minecraft' }
      - { when: directus_enable, project_src: '{{ server_home }}/services/directus' }
      - { when: limesurvey_enable, project_src: '{{ server_home }}/services/limesurvey' }
