- name: Stop home server services
  tags: stop
  block:

  - name: Import enable flags
    include_vars:
      file: vars/main.yml

  - name: Stop Traefik
    docker_compose:
      project_src: '{{ server_home }}/services/traefik'
      stopped: true
      state: present

  - name: Stop WireGuard
    when: '{{ wireguard_enable }}'
    docker_compose:
      project_src: '{{ server_home }}/services/wireguard'
      stopped: true
      state: present

  - name: Stop Bitwarden
    when: '{{ bitwarden_enable }}'
    docker_compose:
      project_src: '{{ server_home }}/services/bitwarden'
      stopped: true
      state: present

  - name: Stop NextCloud
    when: '{{ nextcloud_enable }}'
    docker_compose:
      project_src: '{{ server_home }}/services/nextcloud'
      stopped: true
      state: present

  - name: Stop Pihole
    when: '{{ pihole_enable }}'
    docker_compose:
      project_src: '{{ server_home }}/services/pihole'
      stopped: true
      state: present

  - name: Stop Jellyfin
    when: '{{ jellyfin_enable }}'
    docker_compose:
      project_src: '{{ server_home }}/services/jellyfin'
      stopped: true
      state: present

  - name: Stop Photoprism
    when: '{{ photoprism_enable }}'
    docker_compose:
      project_src: '{{ server_home }}/services/photoprism'
      stopped: true
      state: present
