- name: Boot home server services
  tags: up
  block:

  - name: Boot Traefik
    docker_compose:
      project_src: "{{ services }}/traefik"
      pull: true
      state: present

  - name: Boot Bitwarden
    docker_compose:
      project_src: "{{ services }}/bitwarden"
      pull: true
      state: present

  - name: Boot NextCloud
    docker_compose:
      project_src: "{{ services }}/nextcloud"
      pull: true
      state: present

  - name: Boot Pihole
    docker_compose:
      project_src: "{{ services }}/pihole"
      pull: true
      state: present
