- name: Boot home server services
  tags: up
  block:

  - name: Import enable flags
    include_vars:
      file: vars/main.yml

  - name: Docker compose up
    when: '{{ item.when }}'
    docker_compose:
      project_src: '{{ item.project_src }}'
      pull: true
      state: present
    loop:
      - { when: true, project_src: '{{ server_home }}/services/traefik' }
      - { when: actual_enable, project_src: '{{ server_home }}/services/actual' }
      - { when: affine_enable, project_src: '{{ server_home }}/services/pkms/affine' }
      - { when: bytestash_enable, project_src: '{{ server_home }}/services/bytestash' }
      - { when: change_detection_enable, project_src: '{{ server_home }}/services/detection' }
      - { when: directus_enable, project_src: '{{ server_home }}/services/directus' }
      - { when: docuseal_enable, project_src: '{{ server_home }}/services/docuseal' }
      - { when: gokapi_enable, project_src: '{{ server_home }}/services/media/sharing/gokapi' }
      - { when: grafana_enable, project_src: '{{ server_home }}/services/grafana' }
      - { when: grocy_enable, project_src: '{{ server_home }}/services/grocy' }
      - { when: guacamole_enable, project_src: '{{ server_home }}/services/remote/guacamole' }
      - { when: homarr_enable, project_src: '{{ server_home }}/services/dashboard/homarr' }
      - { when: hortusfox_enable, project_src: '{{ server_home }}/services/inventory/hortusfox' }
      - { when: immich_enable, project_src: '{{ server_home }}/services/media/storage/pictures/immich' }
      - { when: jellyfin_enable, project_src: '{{ server_home }}/services/media/storage/videos/jellyfin' }
      - { when: jetlog_enable, project_src: '{{ server_home }}/services/monitoring/jetlog' }
      - { when: kavita_enable, project_src: '{{ server_home }}/services/media/storage/books/kavita' }
      - { when: kopia_enable, project_src: '{{ server_home }}/services/kopia' }
      - { when: librum_enable, project_src: '{{ server_home }}/services/media/storage/books/librum' }
      - { when: limesurvey_enable, project_src: '{{ server_home }}/services/limesurvey' }
      - { when: minecraft_enable, project_src: '{{ server_home }}/services/minecraft' }
      - { when: navidrome_enable, project_src: '{{ server_home }}/services/media/storage/music/navidrome' }
      - { when: nextcloud_enable, project_src: '{{ server_home }}/services/media/storage/documents/nextcloud' }
      - { when: ntfy_enable, project_src: '{{ server_home }}/services/ntfy' }
      - { when: paperless_enable, project_src: '{{ server_home }}/services/media/storage/documents/paperless' }
      - { when: photoprism_enable, project_src: '{{ server_home }}/services/media/storage/pictures/photoprism' }
      - { when: pihole_enable, project_src: '{{ server_home }}/services/pihole' }
      - { when: prometheus_enable, project_src: '{{ server_home }}/services/prometheus' }
      - { when: stirling_pdf_enable, project_src: '{{ server_home }}/services/stirling-pdf' }
      - { when: unbound_enable, project_src: '{{ server_home }}/services/dns/unbound' }
      - { when: vaultwarden_enable, project_src: '{{ server_home }}/services/vaultwarden' }
      - { when: wazuh_enable, project_src: '{{ server_home }}/services/security/wazuh' }
      - { when: wireguard_easy_enable, project_src: '{{ server_home }}/services/remote/wg-easy' }
      - { when: wireguard_enable, project_src: '{{ server_home }}/services/remote/wireguard' }
      - { when: wishlist_enable, project_src: '{{ server_home }}/services/wishlist' }
