- name: Boot home server services
  tags: up
  block:

  - name: Import enable flags
    include_vars:
      file: vars/main.yml

  - name: Boot Traefik
    docker_compose:
      project_src: '{{ server_home }}/services/traefik'
      pull: true
      state: present

  - name: Boot WireGuard
    when: wireguard_enable
    docker_compose:
      project_src: '{{ server_home }}/services/wireguard'
      pull: true
      state: present

  - name: Boot Bitwarden
    when: bitwarden_enable
    docker_compose:
      project_src: '{{ server_home }}/services/bitwarden'
      pull: true
      state: present

  - name: Boot NextCloud
    when: nextcloud_enable
    docker_compose:
      project_src: '{{ server_home }}/services/nextcloud'
      pull: true
      state: present

  - name: Boot Pihole
    when: pihole_enable
    docker_compose:
      project_src: '{{ server_home }}/services/pihole'
      pull: true
      state: present

  - name: Boot Jellyfin
    when: jellyfin_enable
    docker_compose:
      project_src: '{{ server_home }}/services/jellyfin'
      pull: true
      state: present

  - name: Boot Photoprism
    when: photoprism_enable
    docker_compose:
      project_src: '{{ server_home }}/services/photoprism'
      pull: true
      state: present
