- name: Boot home server services
  tags: up
  block:

  - name: Import enable flags
    include_vars:
      file: vars/main.yml

  - name: Boot Traefik
    docker_compose:
      project_src: '{{ server_home }}/services/traefik'
      pull: true
      state: present

  - name: Boot WireGuard
    when: wireguard_enable
    docker_compose:
      project_src: '{{ server_home }}/services/wireguard'
      pull: true
      state: present

  - name: Boot Guacamole
    when: guacamole_enable
    docker_compose:
      project_src: '{{ server_home }}/services/guacamole'
      pull: true
      state: present

  - name: Boot Pihole
    when: pihole_enable
    docker_compose:
      project_src: '{{ server_home }}/services/pihole'
      pull: true
      state: present

  - name: Boot Grafana
    when: grafana_enable
    docker_compose:
      project_src: '{{ server_home }}/services/grafana'
      pull: true
      state: present

  - name: Boot Prometheus
    when: prometheus_enable
    docker_compose:
      project_src: '{{ server_home }}/services/prometheus'
      pull: true
      state: present

  - name: Boot Ntfy
    when: ntfy_enable
    docker_compose:
      project_src: '{{ server_home }}/services/ntfy'
      pull: true
      state: present

  - name: Boot Limesurvey
    when: limesurvey_enable
    docker_compose:
      project_src: '{{ server_home }}/services/limesurvey'
      pull: true
      state: present

  - name: Boot Bitwarden
    when: bitwarden_enable
    docker_compose:
      project_src: '{{ server_home }}/services/bitwarden'
      pull: true
      state: present

  - name: Boot NextCloud
    when: nextcloud_enable
    docker_compose:
      project_src: '{{ server_home }}/services/nextcloud'
      pull: true
      state: present

  - name: Boot Photoprism
    when: photoprism_enable
    docker_compose:
      project_src: '{{ server_home }}/services/photoprism'
      pull: true
      state: present

  - name: Boot Jellyfin
    when: jellyfin_enable
    docker_compose:
      project_src: '{{ server_home }}/services/jellyfin'
      pull: true
      state: present

  - name: Boot Grocy
    when: grocy_enable
    docker_compose:
      project_src: '{{ server_home }}/services/grocy'
      pull: true
      state: present

  - name: Boot Minecraft
    when: minecraft_enable
    docker_compose:
      project_src: '{{ server_home }}/services/minecraft'
      pull: true
      state: present
