# Wazuh App Copyright (C) 2017, Wazuh Inc. (License GPLv2)
services:
  wazuh.manager:
    container_name: wazuh-manager
    env_file: config/manager.env
    hostname: wazuh.manager
    image: ${WAZUH_MANAGER_IMAGE}
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 10m
    networks:
      app-net:
        ipv4_address: ${WAZUH_MANAGER_IP}
    ports:
      - ${WAZUH_TCP_PORT_1}:1514
      - ${WAZUH_TCP_PORT_2}:1515
      - ${WAZUH_UDP_PORT}:514/udp
      - ${WAZUH_API_PORT}:55000
    restart: unless-stopped
    stop_grace_period: 30s
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 655360
        hard: 655360
    volumes:
      - ./persistence/api_configuration:/var/ossec/api/configuration
      - ./persistence/etc:/var/ossec/etc
      - ./persistence/logs:/var/ossec/logs
      - ./persistence/queue:/var/ossec/queue
      - ./persistence/var_multigroups:/var/ossec/var/multigroups
      - ./persistence/integrations:/var/ossec/integrations
      - ./persistence/active_response:/var/ossec/active-response/bin
      - ./persistence/agentless:/var/ossec/agentless
      - ./persistence/wodles:/var/ossec/wodles
      - ./filebeat-persistence/etc:/etc/filebeat
      - ./filebeat-persistence/var:/var/lib/filebeat
      - ./config/wazuh_indexer_ssl_certs/root-ca-manager.pem:/etc/ssl/root-ca.pem
      - ./config/wazuh_indexer_ssl_certs/wazuh.manager.pem:/etc/ssl/filebeat.pem
      - ./config/wazuh_indexer_ssl_certs/wazuh.manager-key.pem:/etc/ssl/filebeat.key
      - ./config/wazuh_cluster/wazuh_manager.conf:/wazuh-config-mount/etc/ossec.conf

  wazuh.indexer:
    container_name: wazuh-indexer
    env_file: config/indexer.env
    hostname: wazuh.indexer
    image: ${WAZUH_INDEXER_IMAGE}
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 10m
    networks:
      app-net:
        ipv4_address: ${WAZUH_INDEXER_IP}
    ports:
      - ${WAZUH_INDEXER_HTTPS_PORT}:9200
    restart: unless-stopped
    stop_grace_period: 30s
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./indexer-persistence:/var/lib/wazuh-indexer
      - ./config/wazuh_indexer_ssl_certs/root-ca.pem:/usr/share/wazuh-indexer/certs/root-ca.pem
      - ./config/wazuh_indexer_ssl_certs/wazuh.indexer-key.pem:/usr/share/wazuh-indexer/certs/wazuh.indexer.key
      - ./config/wazuh_indexer_ssl_certs/wazuh.indexer.pem:/usr/share/wazuh-indexer/certs/wazuh.indexer.pem
      - ./config/wazuh_indexer_ssl_certs/admin.pem:/usr/share/wazuh-indexer/certs/admin.pem
      - ./config/wazuh_indexer_ssl_certs/admin-key.pem:/usr/share/wazuh-indexer/certs/admin-key.pem
      #  if you need mount a custom opensearch.yml, uncomment the next line and delete the environment variables
      # - ./config/wazuh_indexer/wazuh.indexer.yml:/usr/share/wazuh-indexer/opensearch.yml

  wazuh.dashboard:
    container_name: wazuh-dashboard
    depends_on:
      wazuh.indexer:
        condition: service_started
    env_file: config/dashboard.env
    hostname: wazuh.dashboard
    image: ${WAZUH_DASHBOARD_IMAGE}
    labels:
      - "traefik.enable=true"
      # Routers
      - "traefik.http.routers.wazuh.rule=Host(`seim.${DOMAIN}`)"
      - "traefik.http.routers.wazuh.tls=true"
      # - "traefik.http.routers.wazuh.tls.certresolver=letsencrypt"
      # - "traefik.http.routers.wazuh.tls.domains[0].main=seim.${DOMAIN}"
      - "traefik.http.routers.wazuh.service=wazuh"
      # Services
      - "traefik.http.services.wazuh.loadbalancer.server.port=5601"
    links:
      - wazuh.indexer:wazuh.indexer
      - wazuh.manager:wazuh.manager
    logging:
      driver: json-file
      options:
        max-file: 2
        max-size: 5m
    networks:
      app-net:
        ipv4_address: ${WAZUH_DASHBOARD_IP}
      traefik-net:
        ipv4_address: ${WAZUH_IP}
    ports:
      - 5601
    restart: unless-stopped
    stop_grace_period: 30s
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./dashboard-persistence/config:/usr/share/wazuh-dashboard/data/wazuh/config
      - ./dashboard-persistence/custom:/usr/share/wazuh-dashboard/plugins/wazuh/public/assets/custom
      - ./config/wazuh_indexer_ssl_certs/wazuh.dashboard.pem:/usr/share/wazuh-dashboard/certs/wazuh-dashboard.pem
      - ./config/wazuh_indexer_ssl_certs/wazuh.dashboard-key.pem:/usr/share/wazuh-dashboard/certs/wazuh-dashboard-key.pem
      - ./config/wazuh_indexer_ssl_certs/root-ca.pem:/usr/share/wazuh-dashboard/certs/root-ca.pem
      - ./config/wazuh_dashboard/wazuh.yml:/wazuh-config-mount/data/wazuh/config/wazuh.yml
      #  if you need mount a custom opensearch-dashboards.yml, uncomment the next line and delete the environment variables
      # - ./config/wazuh_dashboard/opensearch_dashboards.yml:/wazuh-config-mount/config/opensearch_dashboards.yml

networks:
  app-net:
    name: wazuh-internal
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${WAZUH_NET}
          gateway: ${WAZUH_GATEWAY}
  traefik-net:
    external: true
    name: traefik-net
