- name: General Security
  hosts: all
  gather_facts: false

  tasks:

  - name: Disable boot from external devices
    tags: init
    block:

    - name: Create fake_usb file
      ansible.builtin.file:
        path: /etc/modprobe.d/fake_usb.conf
        owner: root
        group: root
        mode: 0644
        state: touch

    - name: Add line for configuration
      ansible.builtin.lineinfile:
        path: /etc/modprobe.d/fake_usb.conf
        state: present
        line: install usb-storage /bin/true
        create: true
