services:
  grocy:
    container_name: grocy
    dns:
      - 127.0.0.1
      - 45.90.28.96
      - 45.90.30.96
    env_file: config/.env
    hostname: grocy
    image: ${GROCY_IMAGE}
    labels:
      - "traefik.enable=true"
      # Routers
      - "traefik.http.routers.grocy.entrypoints=web,websecure"
      - "traefik.http.routers.grocy.rule=Host(`grocy.${DOMAIN}`)"
      - "traefik.http.routers.grocy.tls=true"
      # - "traefik.http.routers.grocy.tls.certresolver=letsencrypt"
      # - "traefik.http.routers.grocy.tls.domains[0].main=grocy.${DOMAIN}"
      - "traefik.http.routers.grocy.service=grocy"
      # Services
      - "traefik.http.services.grocy.loadbalancer.server.port=80"
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 10m
    networks:
      traefik-net:
        ipv4_address: ${GROCY_IP}
    ports:
      - 80
    restart: unless-stopped
    stop_grace_period: 30s
    volumes:
      - ./persistence:/config

networks:
  traefik-net:
    external: true
    name: traefik-net
