services:
  prometheus:
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    container_name: prometheus
    hostname: prometheus
    image: ${PROMETHEUS_IMAGE}
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: 5m
    networks:
      app-net:
        ipv4_address: ${PROMETHEUS_INTERNAL_IP}
      monitoring-net:
        ipv4_address: ${PROMETHEUS_IP}
    ports:
      - 9090
    restart: always
    stop_grace_period: 10s
    user: ${DOCKER_UID}:${DOCKER_GID}
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus-persistence:/prometheus

networks:
  app-net:
    name: prometheus-internal
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${PROMETHEUS_NET}
          gateway: ${PROMETHEUS_GATEWAY}
  monitoring-net:
    external: true
    name: monitoring-net
