services:
  detection:
    container_name: change-detection
    dns:
      - 127.0.0.1
      - 1.1.1.1
      - 1.0.0.1
    env_file: config/.env
    hostname: change-detection
    image: ${CHANGE_DETECTION_IMAGE}
    labels:
      - "traefik.enable=true"
      # Routers
      - "traefik.http.routers.change-detection.rule=Host(`detection.${DOMAIN}`)"
      - "traefik.http.routers.change-detection.tls=true"
      # - "traefik.http.routers.change-detection.tls.certresolver=letsencrypt"
      # - "traefik.http.routers.change-detection.tls.domains[0].main=detection.${DOMAIN}"
      - "traefik.http.routers.change-detection.service=change-detection"
      # Services
      - "traefik.http.services.change-detection.loadbalancer.server.port=5000"
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: 10m
    networks:
      traefik-net:
        ipv4_address: ${CHANGE_DETECTION_IP}
    ports:
      - 5000
    restart: always
    stop_grace_period: 10s
    volumes:
      - ./persistence:/datastore

networks:
  traefik-net:
    external: true
    name: traefik-net
