- name: Configure the instance - Home Server - Docker user
  hosts: localhost
  gather_facts: true
  become: true
  become_user: docker
  vars_files:
    - vars/main.yml

  tasks:
#--- Initialization

    - name: Configure Amazon Web Services CLI
      include_tasks:
        file: tasks/aws-cli.yml
      tags: docker

    - name: Set user profile
      include_tasks:
        file: tasks/profile.yml
      tags: docker

    - name: Create log directories
      include_tasks:
        file: services/logs.yml
      tags: docker

    - name: Create persistence directories
      include_tasks:
        file: services/persistence.yml
      tags: docker

    - name: Install docker-compose python package
      include_tasks:
        file: tasks/python.yml
      tags: up

    - name: Initialize and boot all services
      include_tasks:
        file: services/up.yml
      tags: up

    - name: Create InfluxDB retention policies
      include_tasks:
        file: tasks/influxdb.yml
      tags: up

    - name: Create Ntfy default user
      include_tasks:
        file: tasks/ntfy.yml
      tags: up

#--- Docker commands

    - name: Restart all services
      include_tasks:
        file: services/restart.yml
      tags: restart

    - name: Stop all services
      include_tasks:
        file: services/stop.yml
      tags: stop

    - name: Shutdown all services
      include_tasks:
        file: services/down.yml
      tags: down
