services:
  db:
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    container_name: nextcloud-mariadb
    env_file: config/.env.db
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p${NEXTCLOUD_DB_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 5
    hostname: nextcloud-mariadb
    image: ${DEFAULT_DB_IMAGE}
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: 5m
    networks:
      app-net:
        ipv4_address: ${NEXTCLOUD_DB_IP}
    restart: always
    stop_grace_period: 10s
    volumes:
      # Permissions for this folder:
      - ./db-persistence:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro

  redis:
    command: redis-server --requirepass ${NEXTCLOUD_REDIS_PASSWORD}
    container_name: nextcloud-redis
    hostname: nextcloud-redis
    image: ${DEFAULT_REDIS_IMAGE}
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: 5m
    networks:
      app-net:
        ipv4_address: ${NEXTCLOUD_REDIS_IP}
    restart: always
    stop_grace_period: 10s

  cron:
    container_name: nextcloud-cron
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    entrypoint: /cron.sh
    hostname: nextcloud-cron
    image: ${NEXTCLOUD_IMAGE}
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: 5m
    networks:
      app-net:
        ipv4_address: ${NEXTCLOUD_CRON_IP}
    restart: always
    stop_grace_period: 10s
    volumes:
      - ./persistence:/var/www/html

  app:
    container_name: nextcloud
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file: config/.env
    hostname: nextcloud
    image: ${NEXTCLOUD_IMAGE}
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: 10m
    networks:
      app-net:
        ipv4_address: ${NEXTCLOUD_INTERNAL_IP}
    restart: always
    stop_grace_period: 10s
    volumes:
      - ./persistence:/var/www/html

  web:
    container_name: nextcloud-web
    depends_on:
      - app
      - db
      - redis
    hostname: nextcloud-web
    image: ${FASTCGI_SUPPORT_IMAGE}
    labels:
      - "traefik.enable=true"
      # Routers
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.${DOMAIN}`)"
      - "traefik.http.routers.nextcloud.tls=true"
      # - "traefik.http.routers.nextcloud.tls.certresolver=letsencrypt"
      # - "traefik.http.routers.nextcloud.tls.domains[0].main=nextcloud.${DOMAIN}"
      - "traefik.http.routers.nextcloud.service=nextcloud"
      # Services
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
    links:
      - app
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: 5m
    networks:
      app-net:
        ipv4_address: ${NEXTCLOUD_WEB_IP}
      traefik-net:
        ipv4_address: ${NEXTCLOUD_IP}
    restart: always
    stop_grace_period: 10s
    volumes:
      - ./web-persistence/Caddyfile:/etc/caddy/Caddyfile
      - ./web-persistence/data:/data
      - ./web-persistence/config:/config
    volumes_from:
      - app

networks:
  app-net:
    name: nextcloud-internal
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NEXTCLOUD_NET}
          gateway: ${NEXTCLOUD_GATEWAY}
  traefik-net:
    external: true
    name: traefik-net
