services:
  db:
    container_name: "bitwarden-mariadb"
    env_file: "config/db.env"
    hostname: "bitwarden-mariadb"
    image: "mariadb:10.5"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "5m"
    networks:
        app-net:
          ipv4_address: "192.168.11.2"
    restart: "always"
    stop_grace_period: "10s"
    volumes:
      # Permissions for this folder:
      - "./db-persistence:/var/lib/mysql"
      - "/etc/localtime:/etc/localtime:ro"

  app:
    container_name: "bitwarden"
    depends_on:
      - db
    env_file: "config/app.env"
    hostname: "bitwarden"
    image: "vaultwarden/server:1.27.0"
    labels:
      - "traefik.enable=true"
      # Bitwarden UI
      # Routers
      - "traefik.http.routers.bitwarden.rule=Host(`bitwarden.docker.localhost`)"
      - "traefik.http.routers.bitwarden.tls=true"
      - "traefik.http.routers.bitwarden.service=bitwarden"
      # Services
      - "traefik.http.services.bitwarden.loadbalancer.server.port=80"
      # Bitwarden Websocket API
      # Routers
      - "traefik.http.routers.bitwarden-websocket.rule=Host(`bitwarden.docker.localhost`) && Path(`/notifications/hub`)"
      - "traefik.http.routers.bitwarden-websocket.tls=true"
      - "traefik.http.routers.bitwarden-websocket.service=bitwarden-websocket"
      # Services
      - "traefik.http.services.bitwarden-websocket.loadbalancer.server.port=3012"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    networks:
        app-net:
          ipv4_address: "192.168.11.3"
        traefik-net:
          ipv4_address: "192.168.10.4"
    ports:
      - "80"
      - "3012"
    restart: "always"
    stop_grace_period: "10s"
    volumes:
      - "./persistence:/data"

networks:
  app-net:
    name: "bitwarden-internal"
    driver: "bridge"
    ipam:
      driver: "default"
      config:
        - subnet: "192.168.11.0/24"
          gateway: "192.168.11.1"
  traefik-net:
    external: true
    name: "traefik-net"
