services:
  db:
    container_name: "bitwarden-mariadb"
    env_file: "config/db.env"
    hostname: "bitwarden-mariadb"
    image: "${DEFAULT_DB_IMAGE}"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "5m"
    networks:
        app-net:
          ipv4_address: "${BITWARDEN_DB_IP}"
    restart: "always"
    stop_grace_period: "10s"
    volumes:
      # Permissions for this folder:
      - "./db-persistence:/var/lib/mysql"
      - "/etc/localtime:/etc/localtime:ro"

  app:
    container_name: "bitwarden"
    depends_on:
      - db
    env_file: "config/app.env"
    hostname: "bitwarden"
    image: "${BITWARDEN_IMAGE}"
    labels:
      - "traefik.enable=true"
      # Bitwarden UI
      # Routers
      - "traefik.http.routers.bitwarden.rule=Host(`bitwarden.${LOCAL_DOMAIN}`)"
      - "traefik.http.routers.bitwarden.tls=true"
      - "traefik.http.routers.bitwarden.service=bitwarden"
      # Services
      - "traefik.http.services.bitwarden.loadbalancer.server.port=80"
      # Bitwarden Websocket API
      # Routers
      - "traefik.http.routers.bitwarden-websocket.rule=Host(`bitwarden.${LOCAL_DOMAIN}`) && Path(`/notifications/hub`)"
      - "traefik.http.routers.bitwarden-websocket.tls=true"
      - "traefik.http.routers.bitwarden-websocket.service=bitwarden-websocket"
      # Services
      - "traefik.http.services.bitwarden-websocket.loadbalancer.server.port=${BITWARDEN_WEBSOCKET_PORT}"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    networks:
        app-net:
          ipv4_address: "${BITWARDEN_INTERNAL_IP}"
        traefik-net:
          ipv4_address: "${BITWARDEN_IP}"
    ports:
      - "80"
      - "${BITWARDEN_WEBSOCKET_PORT}"
    restart: "always"
    stop_grace_period: "10s"
    user: "${DOCKER_UID}:${DOCKER_GID}"
    volumes:
      - "./persistence:/data"

networks:
  app-net:
    name: "bitwarden-internal"
    driver: "bridge"
    ipam:
      driver: "default"
      config:
        - subnet: "${BITWARDEN_NET}"
          gateway: "${BITWARDEN_GATEWAY}"
  traefik-net:
    external: true
    name: "traefik-net"
