services:
  actual:
    container_name: actual
    dns:
      - 127.0.0.1
      - 45.90.28.96
      - 45.90.30.96
    env_file: config/.env
    hostname: actual
    image: ${ACTUAL_IMAGE}
    labels:
      - "traefik.enable=true"
      # Routers
      - "traefik.http.routers.actual.entrypoints=web,websecure"
      - "traefik.http.routers.actual.rule=Host(`finances.${DOMAIN}`)"
      - "traefik.http.routers.actual.tls=true"
      # - "traefik.http.routers.actual.tls.certresolver=letsencrypt"
      # - "traefik.http.routers.actual.tls.domains[0].main=finances.${DOMAIN}"
      - "traefik.http.routers.actual.service=actual"
      # Services
      - "traefik.http.services.actual.loadbalancer.server.port=5006"
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 10m
    networks:
      traefik-net:
        ipv4_address: ${ACTUAL_IP}
    ports:
      - 5006
    restart: unless-stopped
    stop_grace_period: 30s
    volumes:
      - ./persistence:/data

networks:
  traefik-net:
    external: true
    name: traefik-net
