- name: SSH
  hosts: all
  gather_facts: false
  vars:
    packages:
      - openssh-server

  tasks:
  # Packages
  - name: Packages
    block:

    - name: List packages
      tags: [init, update]
      ansible.builtin.debug:
        msg: "packages: {{ packages }}"

    # sudo apt update -y && sudo apt install -y
    - name: Install
      tags: init
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
        update_cache: true

    # sudo apt update -y && sudo apt upgrade -y
    - name: Upgrade
      tags: update
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: latest
        update_cache: true

  # Configuration
  - name: Configuration
    tags: init
    block:

    # cat -n /etc/ssh/sshd_config
    - name: Update /etc/ssh/sshd_config file - Disable root login
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        search_string: 'PermitRootLogin'
        line: 'PermitRootLogin no'
        owner: root
        group: root
        mode: 0644

    - name: Update /etc/ssh/sshd_config file - Disable empty password
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        search_string: 'PermitEmptyPasswords'
        line: 'PermitEmptyPasswords no'
        owner: root
        group: root
        mode: 0644

  # Service
  - name: Service
    block:

    # systemctl status sshd.service
    - name: Start SSH service
      tags: init
      ansible.builtin.systemd:
        name: ssh
        state: started
        enabled: yes

    - name: Restart SSH service
      tags: update
      ansible.builtin.systemd:
        name: ssh
        state: restarted
        enabled: yes
