- name: XRDP
  hosts: all
  gather_facts: false
  vars:
    packages:
      - xrdp

  tasks:
  # Packages
  - name: Packages
    block:

    - name: List packages
      tags: [init, update]
      ansible.builtin.debug:
        msg: "packages: {{ packages }}"

    # sudo apt update -y && sudo apt install -y
    - name: Install
      tags: init
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
        update_cache: true

    # sudo apt update -y && sudo apt upgrade -y
    - name: Upgrade
      tags: update
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: latest
        update_cache: true

  # Service
  - name: Service
    block:

    # systemctl status xrdp.service
    - name: Start xrdp service
      tags: init
      ansible.builtin.systemd:
        name: xrdp
        state: started
        enabled: yes

    - name: Restart xrdp service
      tags: update
      ansible.builtin.systemd:
        name: xrdp
        state: restarted
        enabled: yes
