- name: XRDP
  hosts: all
  gather_facts: false

  tasks:

  - name: Install and configure XRDP
    tags: init
    become: true
    block:

    - name: Install xrdp
      ansible.builtin.apt:
        pkg:
          - xrdp
        state: latest

    - name: Enable xrdp service
      ansible.builtin.systemd:
        name: xrdp
        enabled: true

    - name: Restart xrdp service
      ansible.builtin.systemd:
        name: xrdp
        state: restarted
