- name: Terraform
  hosts: all
  gather_facts: true
  vars:
    dependencies:
      - gnupg
      - software-properties-common
  vars_files:
    - ../vars/main.yml

  tasks:
  # Dependencies
  - name: Dependencies
    block:

    - name: List dependencies
      tags: [init, update]
      ansible.builtin.debug:
        msg: "dependencies: {{ dependencies }}"

    # sudo apt update -y && sudo apt install -y
    - name: Install dependencies
      tags: init
      ansible.builtin.apt:
        name: "{{ dependencies }}"
        state: present
        update_cache: true

    # sudo apt update -y && sudo apt upgrade -y
    - name: Upgrade dependencies
      tags: update
      ansible.builtin.apt:
        name: "{{ dependencies }}"
        state: latest
        update_cache: true

  # Repository
  - name: Repository
    tags: init
    block:

    - name: Create /etc/apt/keyrings directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: 0755

    # wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null
    - name: Download GPG apt key
      ansible.builtin.uri:
        method: GET
        url: https://apt.releases.hashicorp.com/gpg
        dest: /tmp/terraform.gpg
        follow_redirects: safe
        mode: 0644

    - name: Import GPG key
      ansible.builtin.command:
        cmd: gpg --dearmor --output /etc/apt/keyrings/hashicorp-archive-keyring.gpg --yes /tmp/terraform.gpg

    # echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list > /dev/null
    - name: Add apt repository
      ansible.builtin.apt_repository:
        repo: deb [arch={{ deb_architecture[ansible_architecture] }} signed-by=/etc/apt/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main

    - name: Remove GPG temporary key
      ansible.builtin.file:
        path: /tmp/terraform.gpg
        state: absent

  # Packages
  - name: Packages
    block:

    # sudo apt update -y && sudo apt install -y terraform
    - name: Install
      tags: init
      ansible.builtin.apt:
        name: terraform
        state: present
        update_cache: true

    # sudo apt update -y && sudo apt upgrade -y terraform
    - name: Upgrade
      tags: update
      ansible.builtin.apt:
        name: terraform
        state: latest
        update_cache: true

  # Version
  - name: Version
    tags: [init, update]
    block:

    - name: Confirm version
      ansible.builtin.command:
        cmd: terraform --version
      register: version
      changed_when: false

    - name: Show version
      when: version is defined
      ansible.builtin.debug:
        msg: "Installed version: {{ version.stdout }}"
