services:
  app:
    container_name: grocy
    dns:
      - 127.0.0.1
      - 1.1.1.1
      - 1.0.0.1
    env_file: config/.env
    hostname: grocy
    image: ${GROCY_IMAGE}
    labels:
      - "traefik.enable=true"
      # Routers
      - "traefik.http.routers.grocy.rule=Host(`home.${DOMAIN}`)"
      - "traefik.http.routers.grocy.tls=true"
      # - "traefik.http.routers.grocy.tls.certresolver=letsencrypt"
      # - "traefik.http.routers.grocy.tls.domains[0].main=home.${DOMAIN}"
      - "traefik.http.routers.grocy.service=grocy"
      # Services
      - "traefik.http.services.grocy.loadbalancer.server.port=80"
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: 10m
    networks:
      traefik-net:
        ipv4_address: ${GROCY_IP}
    ports:
      - 80
    restart: always
    stop_grace_period: 10s
    user: ${DOCKER_UID}:${DOCKER_GID}
    volumes:
      - ./persistence:/config

networks:
  traefik-net:
    external: true
    name: traefik-net
