# https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
- name: AWS
  hosts: all
  gather_facts: true
  vars:
    dependencies:
      - zip
  vars_files:
    - ../vars/main.yml

  tasks:
  # Dependencies
  - name: Dependencies
    block:

    - name: List dependencies
      tags: [init, update]
      ansible.builtin.debug:
        msg: "dependencies: {{ dependencies }}"

    # sudo apt update -y && sudo apt install -y
    - name: Install dependencies
      tags: init
      ansible.builtin.apt:
        name: "{{ dependencies }}"
        state: present
        update_cache: true

    # sudo apt update -y && sudo apt upgrade -y
    - name: Upgrade dependencies
      tags: update
      ansible.builtin.apt:
        name: "{{ dependencies }}"
        state: latest
        update_cache: true

  # Install AWS CLI
  - name: Install AWS CLI
    tags: [init, update]
    block:

    # curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    # unzip awscliv2.zip
    - name: Download the installer
      ansible.builtin.unarchive:
        src: "https://awscli.amazonaws.com/awscli-exe-{{ ansible_system | lower }}-{{ ansible_architecture }}.zip"
        dest: "/tmp"
        remote_src: true
        creates: "/tmp/aws"
        mode: 0755

    # sudo ./aws/install
    - name: Install
      ansible.builtin.command:
      args:
        cmd: "/tmp/aws/install"
        creates: /usr/local/bin/aws

    - name: Delete installation directory
      ansible.builtin.file:
        path: /tmp/aws
        state: absent

  # Configure AWS CLI
  - name: Configure AWS CLI
    become_user: ubuntu
    tags: init
    ansible.builtin.shell:
      cmd: aws configure set {{ item.key }} {{ item.value }} --profile {{ aws_profile }}
    no_log: True
    with_dict:
      region: "{{ aws_region }}"
      format: "{{ aws_format }}"
      aws_access_key_id: "{{ aws_access_key }}"
      aws_secret_access_key: "{{ aws_secret_key }}"
