services:
  db:
    command: "--transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW"
    container_name: "nextcloud-mariadb"
    env_file: "config/db.env"
    hostname: "nextcloud-db"
    image: "${NEXTCLOUD_DB_IMAGE}"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "5m"
    networks:
        app-net:
          ipv4_address: "${NEXTCLOUD_DB_IP}"
    restart: "always"
    stop_grace_period: "10s"
    volumes:
      # Permissions for this folder:
      - "./db-persistence:/var/lib/mysql"
      - "/etc/localtime:/etc/localtime:ro"

  redis:
    command: "redis-server --requirepass ${NEXTCLOUD_REDIS_PASSWORD}"
    container_name: "nextcloud-redis"
    hostname: "nextcloud-redis"
    image: "${NEXTCLOUD_REDIS_IMAGE}"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "5m"
    networks:
        app-net:
          ipv4_address: "${NEXTCLOUD_REDIS_IP}"
    restart: "always"
    stop_grace_period: "10s"

  app:
    container_name: "nextcloud"
    depends_on:
      - db
      - redis
    env_file: "config/app.env"
    hostname: "nextcloud"
    image: "${NEXTCLOUD_IMAGE}"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    networks:
        app-net:
          ipv4_address: "${NEXTCLOUD_INTERNAL_IP}"
    restart: "always"
    stop_grace_period: "10s"
    volumes:
      - "./persistence:/var/www/html"

  web:
    container_name: "nextcloud-web"
    depends_on:
      - app
      - db
      - redis
    hostname: "nextcloud-web"
    image: "${NEXTCLOUD_WEB_IMAGE}"
    labels:
      - "traefik.enable=true"
      # Routers
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.docker.localhost`)"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.routers.nextcloud.service=nextcloud"
      - "traefik.http.routers.nextcloud.middlewares=redirect-nextcloud"
      # Services
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      # Middleware
      - "traefik.http.middlewares.redirect-nextcloud.redirectregex.permanent=true"
      - "traefik.http.middlewares.redirect-nextcloud.redirectregex.regex='https://(.*)/.well-known/(?:card|cal)dav'"
      - "traefik.http.middlewares.redirect-nextcloud.redirectregex.replacement='https://$${1}/remote.php/dav'"
    links:
      - app
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "5m"
    networks:
        app-net:
          ipv4_address: "${NEXTCLOUD_WEB_IP}"
        traefik-net:
          ipv4_address: "${NEXTCLOUD_IP}"
    # ports:
    #   - "80"
    restart: "always"
    stop_grace_period: "10s"
    volumes:
      - "./config/nginx.conf:/etc/nginx/nginx.conf:ro"
    volumes_from:
      - app

networks:
  app-net:
    name: "nextcloud-internal"
    driver: "bridge"
    ipam:
      driver: "default"
      config:
        - subnet: "${NEXTCLOUD_NET}"
          gateway: "${NEXTCLOUD_GATEWAY}"
  traefik-net:
    external: true
    name: "traefik-net"
