services:
  # Used for fetching pages via Playwright+Chrome where you need Javascript support.
  playwright-chrome:
    container_name: playwright-chrome
    env_file: config/.env.playwright
    hostname: playwright-chrome
    image: ${PLAYWRIGHT_CHROME_IMAGE}
    logging:
      driver: json-file
      options:
        max-file: 2
        max-size: 2m
    networks:
      app-net:
        ipv4_address: ${CHANGE_DETECTION_PLAYWRIGHT_CHROME_IP}
    restart: unless-stopped
    stop_grace_period: 30s

  detection:
    container_name: change-detection
    depends_on:
      playwright-chrome:
        condition: service_started
    dns:
      - 127.0.0.1
      - 45.90.28.96
      - 45.90.30.96
    env_file: config/.env
    hostname: change-detection
    image: ${CHANGE_DETECTION_IMAGE}
    labels:
      - "traefik.enable=true"
      # Routers
      - "traefik.http.routers.change-detection.rule=Host(`detection.${DOMAIN}`)"
      - "traefik.http.routers.change-detection.tls=true"
      # - "traefik.http.routers.change-detection.tls.certresolver=letsencrypt"
      # - "traefik.http.routers.change-detection.tls.domains[0].main=detection.${DOMAIN}"
      - "traefik.http.routers.change-detection.service=change-detection"
      # Services
      - "traefik.http.services.change-detection.loadbalancer.server.port=5000"
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 10m
    networks:
      app-net:
        ipv4_address: ${CHANGE_DETECTION_INTERNAL_IP}
      traefik-net:
        ipv4_address: ${CHANGE_DETECTION_IP}
    ports:
      - 5000
    restart: unless-stopped
    stop_grace_period: 30s
    volumes:
      - ./persistence:/datastore

networks:
  app-net:
    name: change-detection-internal
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${CHANGE_DETECTION_NET}
          gateway: ${CHANGE_DETECTION_GATEWAY}
  traefik-net:
    external: true
    name: traefik-net
