services:
  it-tools:
    container_name: it-tools
    dns:
      - 127.0.0.1
      - 45.90.28.96
      - 45.90.30.96
    hostname: it-tools
    image: ${IT_TOOLS_IMAGE}
    labels:
      - "traefik.enable=true"
      # Routers
      - "traefik.http.routers.it-tools.entrypoints=web,websecure"
      - "traefik.http.routers.it-tools.rule=Host(`it-tools.${DOMAIN}`)"
      - "traefik.http.routers.it-tools.tls=true"
      # - "traefik.http.routers.it-tools.tls.certresolver=letsencrypt"
      # - "traefik.http.routers.it-tools.tls.domains[0].main=it-tools.${DOMAIN}"
      - "traefik.http.routers.it-tools.service=it-tools"
      # Services
      - "traefik.http.services.it-tools.loadbalancer.server.port=80"
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 10m
    networks:
      traefik-net:
        ipv4_address: ${IT_TOOLS_IP}
    ports:
      - 80
    restart: unless-stopped
    stop_grace_period: 30s

networks:
  traefik-net:
    external: true
    name: traefik-net
