- name: Run APT
  tags: [ init, update ]
  become: true
  block:
  - name: Update cache
    apt:
      update_cache: true

  # apt list --installed
  - name: Install/update packages
    apt:
      pkg:
        - apache2-utils
        - build-essential
        - curl
        - git
        - gnupg
        - htop
        - lsb-release
        - lynis
        - mariadb-client-10.6
        - mariadb-client-core-10.6
        - net-tools
        - openssl
        - pwgen
        - software-properties-common
        - vim
        - zip
      state: latest

  # - name: Remove packages
  #   become: true
  #   apt:
  #     pkg:
  #       -
  #     state: absent

  - name: Remove useless packages from the cache
    apt:
      autoclean: true

  - name: Remove dependencies that are no longer required
    apt:
      autoremove: true
