- name: Run APT
  tags: [ init, update ]
  become: true
  block:
  - name: Update cache
    apt:
      update_cache: true

  # apt list --installed
  - name: Install/update packages
    apt:
      pkg:
        - apache2-utils
        - argon2 # Generate token for Vaultwarden admin interface
        - build-essential
        - curl
        - git
        - gnupg
        - htop
        - lsb-release
        - lynis
        - mariadb-client-10.6 # Execute MariaDB backups for multiple services
        - mariadb-client-core-10.6
        - net-tools
        - openssl
        - postgresql-client-common # Execute PostgreSQL backups for multiple services
        - postgresql-client-14
        - pwgen # Easily generate random password for multiple services
        - python3
        - python3-docker
        - python3-passlib # libraries used by Ansible modules
        - python3-pip
        - software-properties-common
        - vim
        - wireguard
        - zip
      state: latest

  # - name: Remove packages
  #   become: true
  #   apt:
  #     pkg:
  #       -
  #     state: absent

  - name: Remove useless packages from the cache
    apt:
      autoclean: true

  - name: Remove dependencies that are no longer required
    apt:
      autoremove: true
