# sudo crontab -l
- name: Crontab configuration
  tags: docker
  block:

  - name: Databases backup job
    cron:
      name: 'Backup databases (every day before 1AM): Vaultwarden'
      minute: '30'
      hour: '0'
      job: '{{ item }}'
      state: present
    loop:
      - 'source ${SERVER_HOME}/env/.env; mysqldump -h ${VAULTWARDEN_DB_IP} -u ${VAULTWARDEN_DB_USER} -p${VAULTWARDEN_DB_PASSWORD} vaultwarden_db > ${SERVER_HOME}/services/kopia/persistence/databases/vaultwarden.sql'

  - name: Files backup job
    cron:
      name: 'Backup files (every day before 1AM): Vaultwarden'
      minute: '30'
      hour: '0'
      job: '{{ item }}'
      state: present
    loop:
      - 'source ${SERVER_HOME}/env/.env; tar -cf ${SERVER_HOME}/services/kopia/persistence/files/vaultwarden_rsa_keys.tar ${SERVER_HOME}/services/vaultwarden/persistence/rsa_key*'
