- name: Crontab configuration
  tags: init
  become: true
  block:

  - name: Daily backup job, every day at 4AM
    cron:
      name: "Backup services: Bitwarden"
      hour: "4"
      job: "/opt/home-server/scripts/backup/all.sh daily"
      state: "present"

  - name: Weekly backup job, every Monday morning at 3AM
    cron:
      name: "Backup services: ..."
      hour: "3"
      job: "/opt/home-server/scripts/backup/all.sh weekly"
      state: "present"
      weekday: "1"

  - name: Monthly backup job, every 1st of the month at 2AM
    cron:
      name: "Backup services: ..."
      day: "1"
      hour: "2"
      job: "/opt/home-server/scripts/backup/all.sh monthly"
      state: "present"

  - name: Yearly backup job, every 1st of the year at 1AM
    cron:
      name: "Backup services: ..."
      day: "1"
      hour: "1"
      job: "/opt/home-server/scripts/backup/all.sh yearly"
      month: "1"
      state: "present"
