- name: Initialization
  tags: init
  block:
  # sudo groupadd -g 1001 docker
  - name: Create docker group
    become: true
    group:
      name: docker
      gid: '{{ docker_gid }}'
      state: present

  # sudo useradd -c "Docker" -g docker -m -d /home/docker -s /bin/bash -u 1001 docker
  - name: Create docker user
    become: true
    user:
      name: docker
      comment: Docker
      group: docker
      home: /home/docker
      shell: /bin/bash
      state: present
      uid: '{{ docker_uid }}'

- name: Install/update required system packages
  become: true
  apt:
    pkg:
      - ca-certificates
      - curl
      - gnupg
    state: latest
    update_cache: true
  tags: [ init, update ]

- name: Initialization
  tags: init
  block:
  - name: Add Docker GPG apt key
    become: true
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker repository
    become: true
    apt_repository:
      repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
      state: present

- name: Update apt and install/update Docker Engine
  become: true
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true
  tags: [ init, update ]

- name: Enable Docker service
  become: true
  systemd:
    name: docker
    state: started
    enabled: yes
  tags: init

- name: Restart Docker service
  become: true
  systemd:
    name: docker
    state: restarted
    enabled: yes
  tags: update
