- name: Initialization
  tags: init
  become: true
  block:
  # sudo groupadd -g 1001 docker
  - name: Create docker group
    group:
      name: docker
      gid: '{{ docker_gid }}'
      state: present

  # sudo useradd -c "Docker" -g docker -m -d /home/docker -s /bin/bash -u 1001 docker
  - name: Create docker user
    user:
      name: docker
      comment: Docker
      group: docker
      home: /home/docker
      shell: /bin/bash
      state: present
      uid: '{{ docker_uid }}'

- name: Install/update required system packages
  tags: [ init, update ]
  become: true
  apt:
    pkg:
      - ca-certificates
      - curl
      - gnupg
    state: latest
    update_cache: true

- name: Initialization
  tags: init
  become: true
  block:

  - name: Create /etc/apt/keyrings directory
    file:
      path: /etc/apt/keyrings
      state: directory
      mode: 0755

  - name: Add Docker GPG apt key
    get_url:
      url: https://download.docker.com/linux/ubuntu/gpg
      dest: /tmp/docker.gpg
      mode: 0644

  - name: Import Docker GPG key
    command: gpg --dearmor -o /etc/apt/keyrings/docker.gpg /tmp/docker.gpg

  - name: Add Docker APT repository
    shell: |
      echo 'deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable' | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: Update apt cache and install/update Docker Engine
  tags: [ init, update ]
  become: true
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true

- name: Enable Docker service
  tags: init
  become: true
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Restart Docker service
  tags: update
  become: true
  systemd:
    name: docker
    state: restarted
    enabled: yes
