- name: Change permissions of home server directory recursively
  tags: init
  become: true
  file:
      path: '{{ server_home }}'
      state: directory
      owner: docker
      group: docker
      recurse: true
