- name: Apply dotfiles for ubuntu user
  tags: init
  copy:
    src: '{{ server_home }}/dotfiles_ubuntu/'
    dest: /home/ubuntu/
    owner: ubuntu
    group: ubuntu
    mode: 0644

- name: Apply dotfiles for docker user
  tags: docker
  copy:
    src: '{{ server_home }}/dotfiles_docker/'
    dest: /home/docker/
    owner: docker
    group: docker
    mode: 0644

- name: Update SERVER_HOME
  tags: docker
  lineinfile:
      path: /home/docker/.bashrc
      state: present
      search_string: 'SERVER_HOME'
      line: 'SERVER_HOME={{ server_home }}'
