- name: Install/Update openssh-server package
  tags: [ init, update ]
  become: true
  apt:
    pkg:
      - openssh-server
    state: latest
    update_cache: true

- name: Initialize SSH
  tags: init
  become: true
  block:
  # cat -n /etc/ssh/sshd_config
  - name: Update /etc/ssh/sshd_config file - Disable root login
    lineinfile:
      path: /etc/ssh/sshd_config
      state: present
      search_string: 'PermitRootLogin'
      line: 'PermitRootLogin no'
      owner: root
      group: root
      mode: 0644
  - name: Update /etc/ssh/sshd_config file - Disable empty password
    lineinfile:
      path: /etc/ssh/sshd_config
      state: present
      search_string: 'PermitEmptyPasswords'
      line: 'PermitEmptyPasswords no'
      owner: root
      group: root
      mode: 0644
  # systemctl status sshd.service
  - name: Enable SSH service
    systemd:
      name: ssh
      state: started
      enabled: yes
  # sudo ufw status
  - name: Add rule to the firewall
    ufw:
      rule: limit
      #name: OpenSSH
      port: 22
      protocol: tcp
      log: true

- name: Update SSH
  tags: update
  become: true
  block:
  - name: Restart SSH service
    systemd:
      name: ssh
      state: restarted
      enabled: yes
