- name: Install and configure XRDP
  tags: init
  become: true
  block:

  - name: Install xrdp
    apt:
      pkg:
        - xrdp
      state: latest

  - name: Enable xrdp service
    systemd:
      name: xrdp
      enabled: true

  - name: Restart xrdp service
    systemd:
      name: xrdp
      state: restarted
