services:
  kopia:
    command: server start --disable-csrf-token-checks --insecure --address=0.0.0.0:51515
    container_name: kopia
    dns:
      - 127.0.0.1
      - 45.90.28.96
      - 45.90.30.96
    env_file: config/.env
    hostname: kopia
    image: ${KOPIA_IMAGE}
    labels:
      - "traefik.enable=true"
      # Routers
      - "traefik.http.routers.kopia.rule=Host(`kopia.${DOMAIN}`)"
      - "traefik.http.routers.kopia.tls=true"
      # - "traefik.http.routers.kopia.tls.certresolver=letsencrypt"
      # - "traefik.http.routers.kopia.tls.domains[0].main=kopia.${DOMAIN}"
      - "traefik.http.routers.kopia.service=kopia"
      # Services
      - "traefik.http.services.kopia.loadbalancer.server.port=51515"
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 10m
    networks:
      traefik-net:
        ipv4_address: ${KOPIA_IP}
    # Setup the server that provides the web gui
    ports:
      - 51515
    restart: unless-stopped
    stop_grace_period: 30s
    volumes:
      # Mount local folders needed by kopia
      - ./persistence/config:/app/config
      - ./persistence/cache:/app/cache
      - ./persistence/logs:/app/logs
      # Mount local folders to snapshot
      - ./persistence/databases:/data/databases:ro
      - ./persistence/files:/data/files:ro
      #- ${SERVER_HOME}/services/media/storage/pictures/immich/persistence:/data/immich:ro
      #- ${SERVER_HOME}/services/media/storage/videos/jellyfin/persistence:/data/jellyfin:ro
      #- ${SERVER_HOME}/services/vaultwarden/persistence:/data/vaultwarden:ro

networks:
  traefik-net:
    external: true
    name: traefik-net
